import React, { useState, useEffect } from 'react';
import {
  FileText,
  Copy,
  Download,
  Printer,
  Sparkles,
  Save,
  CheckCircle2,
  Calendar,
  Clock,
  TrendingUp,
  AlertCircle,
  Share2,
} from 'lucide-react';
import { useWork } from '../../context/WorkContext';
import { DailyReportItem } from '../../types';

export const DailyReportView: React.FC = () => {
  const { tasks, projects, reports, addReport, updateReport } = useWork();

  const [selectedDate, setSelectedDate] = useState('2026-09-15');
  const [achievements, setAchievements] = useState('');
  const [challenges, setChallenges] = useState('');
  const [tomorrowPlan, setTomorrowPlan] = useState('');
  const [notes, setNotes] = useState('');
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);

  // Compute stats for selectedDate
  const dateTasks = tasks.filter((t) => t.dueDate === selectedDate);
  const completed = dateTasks.filter((t) => t.status === 'Completed').length;
  const inProgress = dateTasks.filter((t) => t.status === 'In Progress').length;
  const pending = dateTasks.filter((t) => t.status === 'Pending').length;
  const productivity = dateTasks.length > 0 ? Math.round((completed / dateTasks.length) * 100) : 0;
  const totalMinutes = dateTasks.reduce(
    (acc, t) => acc + (t.actualMinutes || t.estimatedMinutes || 0),
    0
  );

  // Check if a report for this date already exists
  const existingReport = reports.find((r) => r.date === selectedDate);

  useEffect(() => {
    if (existingReport) {
      setAchievements(existingReport.achievements || '');
      setChallenges(existingReport.challenges || '');
      setTomorrowPlan(existingReport.tomorrowPlan || '');
      setNotes(existingReport.notes || '');
    } else {
      // Default smart compilation
      const completedTasks = dateTasks.filter((t) => t.status === 'Completed');
      const uncompletedTasks = dateTasks.filter((t) => t.status !== 'Completed');

      setAchievements(
        completedTasks.length > 0
          ? `• Successfully delivered ${completedTasks.length} task(s):\n` +
              completedTasks.map((t) => `  - ${t.title}`).join('\n')
          : '• Commenced milestone implementation and scheduled reviews.'
      );
      setChallenges(
        '• Minor dependency updates and waiting for feedback on client portal designs.'
      );
      setTomorrowPlan(
        uncompletedTasks.length > 0
          ? `• Complete carry-over tasks:\n` +
              uncompletedTasks.map((t) => `  - ${t.title}`).join('\n') +
              `\n• Review database indexing and run automated integration test suite.`
          : '• Kick off next milestone sprint tasks and sync with team leads.'
      );
      setNotes('Logged all actual task times accurately.');
    }
  }, [selectedDate, existingReport, tasks]);

  const handleSaveReport = async () => {
    const reportPayload = {
      date: selectedDate,
      title: `Daily Work Report - ${selectedDate}`,
      totalTasks: dateTasks.length,
      completedTasks: completed,
      inProgressTasks: inProgress,
      pendingTasks: pending,
      productivity,
      totalHours: Number((totalMinutes / 60).toFixed(1)),
      achievements,
      challenges,
      tomorrowPlan,
      notes,
    };

    if (existingReport) {
      await updateReport(existingReport.id, reportPayload);
    } else {
      await addReport(reportPayload);
    }

    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  };

  const generateReportText = () => {
    return (
      `========================================\n` +
      `DAILY WORK REPORT - ${selectedDate}\n` +
      `========================================\n\n` +
      `METRICS SUMMARY:\n` +
      `- Total Tasks Planned: ${dateTasks.length}\n` +
      `- Tasks Completed: ${completed}\n` +
      `- Tasks In Progress: ${inProgress}\n` +
      `- Tasks Pending: ${pending}\n` +
      `- Productivity Rating: ${productivity}%\n` +
      `- Total Work Hours Logged: ${(totalMinutes / 60).toFixed(1)} hrs\n\n` +
      `KEY ACHIEVEMENTS:\n` +
      `${achievements}\n\n` +
      `CHALLENGES & BLOCKERS:\n` +
      `${challenges}\n\n` +
      `PLAN FOR TOMORROW:\n` +
      `${tomorrowPlan}\n\n` +
      `ADDITIONAL NOTES:\n` +
      `${notes}\n` +
      `========================================\n` +
      `Generated by Daily Work Manager SaaS\n`
    );
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateReportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportCSV = () => {
    const rows = [
      ['Metric', 'Value'],
      ['Date', selectedDate],
      ['Total Tasks', dateTasks.length.toString()],
      ['Completed', completed.toString()],
      ['In Progress', inProgress.toString()],
      ['Pending', pending.toString()],
      ['Productivity (%)', `${productivity}%`],
      ['Total Hours', (totalMinutes / 60).toFixed(1)],
      ['Achievements', `"${achievements.replace(/"/g, '""')}"`],
      ['Challenges', `"${challenges.replace(/"/g, '""')}"`],
      ['Tomorrow Plan', `"${tomorrowPlan.replace(/"/g, '""')}"`],
    ];

    const csvContent = 'data:text/csv;charset=utf-8,' + rows.map((e) => e.join(',')).join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `Daily_Report_${selectedDate}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div id="daily-report-view" className="space-y-6 max-w-5xl mx-auto pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl md:text-2xl font-extrabold text-slate-900 dark:text-white font-['Outfit'] tracking-tight">
            Daily Work Report
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Auto-compiled executive overview of tasks, productivity, and forward commitments
          </p>
        </div>

        {/* Date Selector & Export Actions */}
        <div className="flex flex-wrap items-center gap-2">
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-xs">
            <Calendar className="w-3.5 h-3.5 text-indigo-500" />
            <input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="bg-transparent text-slate-900 dark:text-white font-medium outline-none"
            />
          </div>

          <button
            onClick={handleCopy}
            className="px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-semibold flex items-center gap-1.5 transition-colors"
            title="Copy formatted report to clipboard"
          >
            <Copy className="w-3.5 h-3.5" />
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>

          <button
            onClick={handleExportCSV}
            className="px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-semibold flex items-center gap-1.5 transition-colors"
            title="Download CSV"
          >
            <Download className="w-3.5 h-3.5" />
            <span>CSV</span>
          </button>

          <button
            onClick={handlePrint}
            className="px-3 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-semibold flex items-center gap-1.5 transition-colors"
            title="Print / Save as PDF"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>PDF / Print</span>
          </button>

          <button
            onClick={handleSaveReport}
            className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold shadow-xs flex items-center gap-1.5 transition-colors"
          >
            <Save className="w-3.5 h-3.5" />
            <span>{saved ? 'Saved to DB!' : 'Save Report'}</span>
          </button>
        </div>
      </div>

      {/* Report Container */}
      <div className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xs p-6 md:p-8 space-y-6 print:border-none print:shadow-none">
        {/* Report Banner */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-6 border-b border-slate-100 dark:border-slate-800 gap-4">
          <div>
            <span className="text-[11px] font-bold uppercase tracking-widest text-indigo-600 dark:text-indigo-400">
              Executive Daily Briefing
            </span>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mt-1">
              Work Report for{' '}
              {new Date(`${selectedDate}T00:00`).toLocaleDateString('en-US', {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}
            </h2>
          </div>
          <div className="flex items-center gap-2">
            <span className="px-3 py-1 rounded-full bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300 text-xs font-bold border border-emerald-200 dark:border-emerald-800">
              {productivity}% Productivity
            </span>
          </div>
        </div>

        {/* Metrics Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
            <span className="text-[11px] text-slate-400 font-medium uppercase">Tasks Planned</span>
            <p className="text-2xl font-bold text-slate-900 dark:text-white mt-1 font-['Outfit']">
              {dateTasks.length}
            </p>
          </div>
          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
            <span className="text-[11px] text-emerald-600 font-medium uppercase">Completed</span>
            <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400 mt-1 font-['Outfit']">
              {completed}
            </p>
          </div>
          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
            <span className="text-[11px] text-indigo-600 font-medium uppercase">In Progress</span>
            <p className="text-2xl font-bold text-indigo-600 dark:text-indigo-400 mt-1 font-['Outfit']">
              {inProgress}
            </p>
          </div>
          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
            <span className="text-[11px] text-indigo-600 font-medium uppercase">Hours Logged</span>
            <p className="text-2xl font-bold text-slate-900 dark:text-white mt-1 font-['Outfit']">
              {(totalMinutes / 60).toFixed(1)} hrs
            </p>
          </div>
        </div>

        {/* Tasks Included in this date */}
        <div>
          <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider mb-2">
            Work Items for this Date ({dateTasks.length})
          </h3>
          <div className="divide-y divide-slate-100 dark:divide-slate-800 border border-slate-100 dark:border-slate-800 rounded-2xl overflow-hidden">
            {dateTasks.map((t) => (
              <div key={t.id} className="p-3 flex items-center justify-between text-xs">
                <div className="flex items-center gap-2">
                  <CheckCircle2
                    className={`w-4 h-4 ${
                      t.status === 'Completed' ? 'text-emerald-500' : 'text-slate-300'
                    }`}
                  />
                  <span
                    className={`font-medium ${
                      t.status === 'Completed' ? 'line-through text-slate-400' : ''
                    }`}
                  >
                    {t.title}
                  </span>
                </div>
                <span className="text-slate-400 font-mono">
                  {t.actualMinutes || t.estimatedMinutes}m | {t.status}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Editable Report Content Blocks */}
        <div className="space-y-4">
          <div>
            <label className="block text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider mb-1.5">
              1. Key Achievements & Completed Milestones
            </label>
            <textarea
              rows={3}
              value={achievements}
              onChange={(e) => setAchievements(e.target.value)}
              placeholder="Detail major milestones achieved..."
              className="w-full p-3 text-xs rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white outline-none focus:border-indigo-500"
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider mb-1.5">
              2. Challenges, Blockers & Mitigations
            </label>
            <textarea
              rows={2}
              value={challenges}
              onChange={(e) => setChallenges(e.target.value)}
              placeholder="Any dependencies, blockers, or technical issues..."
              className="w-full p-3 text-xs rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white outline-none focus:border-indigo-500"
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider mb-1.5">
              3. Tomorrow's Focus & Action Plan
            </label>
            <textarea
              rows={2}
              value={tomorrowPlan}
              onChange={(e) => setTomorrowPlan(e.target.value)}
              placeholder="Target objectives for the next business day..."
              className="w-full p-3 text-xs rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white outline-none focus:border-indigo-500"
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider mb-1.5">
              4. Additional Notes / Retrospective
            </label>
            <textarea
              rows={2}
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Miscellaneous reflections, client notes, or ideas..."
              className="w-full p-3 text-xs rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white outline-none focus:border-indigo-500"
            />
          </div>
        </div>

        {/* Footer save note */}
        <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs text-slate-400">
          <span>Persists securely to user Firestore database & offline storage.</span>
          <button
            onClick={handleSaveReport}
            className="text-indigo-600 dark:text-indigo-400 font-semibold hover:underline"
          >
            Save Changes
          </button>
        </div>
      </div>
    </div>
  );
};
